image: python:3.7

stages:
  - test
  - dev

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: eu-west-2

test:
  stage: test
  before_script:
    - echo "FLASK_ENV=testing"
    - echo $AWS_ACCESS_KEY_ID
    - echo $AWS_SECRET_ACCESS_KEY
    - pip install -r requirements.txt
  script:
    - python --version
    - echo "Running tests"
    - python -m pytest tests
  only:
  - dev

dev:
  stage: dev
  script:
    - echo "Testing flask app launch"
    - python --version
    - echo "FLASK_ENV=development"
    - echo "FLASK_APP=app.py"
    - python app.py
  environment:
    name: dev
  only:
  - dev