image: python:3.7

stages:
  - test
  - deploy

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: eu-west-2

test:
  stage: test
  before_script:
    - echo "FLASK_ENV=testing"
    - echo $AWS_ACCESS_KEY_ID
    - echo $AWS_SECRET_ACCESS_KEY
    - pip install -r requirements.txt
  environment:
    name: dev
  script:
    - python --version
    - echo "Running tests"
    - python -m pytest tests
    - echo "Testing flask app"
    - echo "FLASK_ENV=development"
    - echo "FLASK_APP=application.py"
  only:
  - dev
  - master

deploy:
  stage: deploy
  before_script:
    - echo "FLASK_ENV=deployment"
    - echo $AWS_ACCESS_KEY_ID
    - echo $AWS_SECRET_ACCESS_KEY
    - pip install awscli # Install the SDK
    - pip install awsebcli --upgrade --user
    - echo "[profile eb-cli]"
  script:
    - python --version
    - echo "Deploying Flask application"
    - echo "FLASK_APP=application.py"
    - /root/.local/bin/eb deploy prme-env
  environment:
    name: prod
  only:
  - deploy