explainers:
  rod_task:
    tokenizer_path: 'data/pickles/tokenizer.pickle'
    name: 'Risk of death'
    class_names:
      - 'Not Likely To Die'
      - 'Likely To Die'

    fasttext:
      model_name: 'fasttext_def_v2'
      version: 2.0
      path: 'models/fasttext_def_v2/'
      risk_path: 'data/pickles/fasttext_risk.pickle'

    1d_cnn:
      model_name: '1d_cnn_def_v2'
      version: 2.0
      path: 'models/1d_cnn_def_v2/'
      risk_path: 'data/pickles/1d_cnn_risk.pickle'

  rohr_task:
    tokenizer_path: 'data/pickles/tokenizer_readm.pickle'
    name: 'Risk of hospital readmission'
    class_names:
      - 'Not Likely For Readmission'
      - 'Likely For Readmission'

    fasttext:
      model_name: 'fasttext_def_v2_readm'
      version: 2.0
      path: 'models/fasttext_def_v2_readm/'
      risk_path: 'data/pickles/fasttext_risk_readm.pickle'

    1d_cnn:
      model_name: '1d_cnn_def_v2_readm'
      version: 2.0
      path: 'models/1d_cnn_def_v2_readm/'
      risk_path: 'data/pickles/1d_cnn_risk_readm.pickle'







