AWSConfigurationTemplateVersion: 1.1.0.0
OptionSettings:
  aws:elasticbeanstalk:environment:
    EnvironmentType: SingleInstance
  aws:autoscaling:launchconfiguration:
    IamInstanceProfile: aws-eb-role-full
  aws:ec2:instances:
    EnableSpot: true
    InstanceTypes: 'g3s.xlarge, p3.2xlarge'
CName: prme-main
EnvironmentTier:
  Type: Standard
  Name: WebServer